name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Clean Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: wish44165
          template: classic
          # Stripped down base: only basic header and repository stats
          base: header, repositories
          config_timezone: Australia/Melbourne
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 5
